%% Coherent sigma series for the eta=0.5-fixed, LCR-mu estimation.
addpath('functions'); addpath('functions/chi'); addpath('data'); addpath('utils');
matching_type = 1; pi_eu_ss = 1; pi_us_ss = 1;
load('data/LFX_data.mat'); load('data/calibration.mat');
run('functions/params.m');
T = length(mu_us);
R = load('_estimation_result_eta50_lcr.mat');
in = struct('mu_us', mu_minus_lcr_level(mu_us, LCR_us), 'mu_eu', mu_eu, ...
    'im_us', im_us, 'im_eu', im_eu, 'TED_s_us_t', TED_s_us_t, 'TED_s_eu_t', TED_s_eu_t, ...
    'matching_type', 1, 'varrho', 0, 'freq', freq, 'pi_us_ss', 1, 'pi_eu_ss', 1, ...
    'use_mu_baseline', 0, 'mubar_us_t', zeros(T,1), 'mubar_eu_t', zeros(T,1), ...
    'sigma_us_init', sigma_us, 'sigma_eu_init', sigma_eu, 'abs_scale', 12e4);
out = run_filter_series(R.lambda_opt, R.eta_opt, R.iota_ss_opt, ploss_us, in);
writetable(table(out.sigma_us_t, out.sigma_eu_t, 'VariableNames', {'sigma_us','sigma_eu'}), ...
    'RW_shock_est_eta50_lcr.csv');
fprintf('RW_shock_est_eta50_lcr.csv: lam=%.3f eta=%.3f iota=%.4f | mean=%.4f max=%.2f\n', ...
    R.lambda_opt, R.eta_opt, R.iota_ss_opt, mean(out.sigma_us_t), max(out.sigma_us_t));
